try

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -8,15 +8,267 @@ on:
     
 jobs:
   api-tests:
-    uses: ./.github/workflows/api-test.yml
-    secrets: inherit
+    runs-on: ubuntu-latest
+    env:
+      METADATA_REPORT_PATH: /tmp/metadata.toml
+      XUNIT_REPORT_PATH: ${{ github.workspace }}/reports/pytest-report.xml    
+    permissions:
+      id-token: write # This is required for requesting the Github JWT
+      contents: read # This is required for actions/checkout
+    strategy:
+      fail-fast: false
+      matrix:		
+        conf: ["sha256", "murmur128"]
+        db: ["mongo7", "postgres15"]
+        cache_db: ["redis7"]
+        pump: ["tykio/tyk-pump-docker-pub:v1.8", "$ECR/tyk-pump:master"]
+        sink: ["tykio/tyk-mdcb-docker:v2.4", "$ECR/tyk-sink:master"]
+        exclude: 
+          - pump: tykio/tyk-pump-docker-pub:v1.8
+            sink: $ECR/tyk-sink:master
+          - pump: $ECR/tyk-pump:master
+            sink: tykio/tyk-mdcb-docker:v2.4
+          - db: mongo7
+            conf: murmur128
+          - db: postgres15
+            conf: sha256
+        include:
+          - db: postgres15
+            markers: "and not sql"
+    steps:
+      - uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
+          role-session-name: cipush
+          aws-region: eu-central-1
+      - id: ecr
+        uses: aws-actions/amazon-ecr-login@v2
+        with:
+          mask-password: 'true'
+          # Only ${{ github.actor }} has access
+          # See https://github.com/mxschmitt/action-tmate#use-registered-public-ssh-keys
+      - name: Setup tmate session only in debug mode
+        uses: mxschmitt/action-tmate@v3
+        if: runner.debug == '1'
+        with:
+          detached: true
+          limit-access-to-actor: true
+      - name: fetch env from tyk-ci
+        uses: actions/checkout@v3
+      - name: env up
+        shell: bash
+        working-directory: auto
+        id: env_up
+        env:
+          pull_policy: 'if_not_present'
+          GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
+          TYK_DB_LICENSEKEY: ${{ secrets.DASH_LICENSE }}
+          TYK_MDCB_LICENSE: ${{ secrets.MDCB_LICENSE }}
+          ECR: ${{ steps.ecr.outputs.registry }}
+        run: |
+          echo "ECR=${ECR}
+          tyk_image=$ECR/tyk:master
+          tyk_analytics_image=$ECR/tyk-analytics:master
+          # alfa and beta have to come after the override
+          tyk_alfa_image=$tyk_image
+          tyk_beta_image=$tyk_image
+          tyk_pump_image=${{matrix.pump}}
+          tyk_sink_image=${{matrix.sink}}
+          confs_dir=./pro-ha
+          env_file=local-${{ matrix.db }}.env" > versions.env
+          echo "::group::versions"
+          cat versions.env
+          echo "::endgroup::"
+          # Add Tyk component config variations to $env_file
+          cat confs/${{ matrix.conf }}.env >> local-${{ matrix.db }}.env
+          # bring up env, the project name is important
+          docker compose -p auto -f pro-ha.yml -f deps_pro-ha.yml -f ${{ matrix.db }}.yml -f ${{ matrix.cache_db }}.yml --env-file versions.env --profile master-datacenter up --quiet-pull -d
+          ./dash-bootstrap.sh http://localhost:3000
+          docker compose -p auto -f pro-ha.yml -f deps_pro-ha.yml -f ${{ matrix.db }}.yml -f ${{ matrix.cache_db }}.yml --env-file versions.env --profile slave-datacenter up --quiet-pull -d
+      - name: Run tests
+        working-directory: auto
+        id: test_execution
+        run: |
+          # Generate report id
+          echo "id=$(date +%s%N)" >> $GITHUB_OUTPUT
+          # Run tests
+          set -o pipefail
+          echo "### API tests ${{ matrix.db }} ${{ matrix.conf }}" >> $GITHUB_STEP_SUMMARY
+          if docker run --rm --network auto_default --env-file pytest.env -v ${{ github.workspace }}/reports:/app/reports \
+            ${{ steps.ecr.outputs.registry }}/tyk-automated-tests:master \
+            pytest -c pytest_ci.ini --junitxml=./${XUNIT_REPORT_PATH#"${{ github.workspace }}"} --ci -m "not local and not dind ${{ matrix.markers }}" | tee tests.out; then
+              echo "All tests passed!" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "::error title=API tests ${{ matrix.db }} ${{ matrix.conf }}::Test execution failed"
+            cat tests.out >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+      - name: Docker logs for all components
+        if: failure() && (steps.test_execution.outcome != 'success' || steps.env_up.outcome != 'success')
+        working-directory: auto
+        env:
+          pull_policy: 'if_not_present'
+          GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
+          TYK_DB_LICENSEKEY: ${{ secrets.DASH_LICENSE }}
+          TYK_MDCB_LICENSE: ${{ secrets.MDCB_LICENSE }}
+          ECR: ${{ steps.ecr.outputs.registry }}
+        run: |
+          docker compose -p auto -f pro-ha.yml -f deps_pro-ha.yml -f ${{ matrix.db }}.yml -f ${{ matrix.cache_db }}.yml --env-file versions.env --profile all logs | sort > ${{ github.workspace }}/docker-compose.log
+          echo "::group::DockerLogs"
+          cat ${{ github.workspace }}/docker-compose.log
+          echo "::endgroup::"
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        if: failure() && (steps.test_execution.outcome != 'success' || steps.env_up.outcome != 'success')
+        with:
+          name: docker-compose-logs-${{ github.job }}-${{ matrix.db }}-${{ matrix.conf }}-${{ github.run_id }}
+          path: ${{ github.workspace }}/docker-compose.log
+          retention-days: 3
+          overwrite: true
   ui-tests:
-    uses: ./.github/workflows/ui-test.yml
-    secrets: inherit
+    runs-on: ubuntu-latest
+    env:
+      METADATA_REPORT_PATH: /tmp/metadata.toml
+      XUNIT_REPORT_PATH: ${{ github.workspace }}/tests/ui/playwright-report/results.xml
+    permissions:
+      id-token: write # This is required for requesting the Github JWT
+      contents: read # This is required for actions/checkout
+    strategy:
+      fail-fast: false
+      matrix:		
+        conf: ["sha256", "murmur128"]
+        db: ["mongo7", "postgres15"]
+        cache_db: ["redis7"]
+        pump: ["tykio/tyk-pump-docker-pub:v1.8", "$ECR/tyk-pump:master"]
+        sink: ["tykio/tyk-mdcb-docker:v2.4", "$ECR/tyk-sink:master"]
+        exclude: 
+          - pump: tykio/tyk-pump-docker-pub:v1.8
+            sink: $ECR/tyk-sink:master
+          - pump: $ECR/tyk-pump:master
+            sink: tykio/tyk-mdcb-docker:v2.4
+          - db: mongo7
+            conf: murmur128
+          - db: postgres15
+            conf: sha256
+        include:
+          - db: postgres15
+            markers: "and not sql"          
+    steps:
+      - uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
+          role-session-name: cipush
+          aws-region: eu-central-1
+      - id: ecr
+        uses: aws-actions/amazon-ecr-login@v2
+        with:
+          mask-password: 'true'
+          # Only ${{ github.actor }} has access
+          # See https://github.com/mxschmitt/action-tmate#use-registered-public-ssh-keys
+      - name: Setup tmate session only in debug mode
+        uses: mxschmitt/action-tmate@v3
+        if: runner.debug == '1'
+        with:
+          detached: true
+          limit-access-to-actor: true
+      - name: fetch env from tyk-ci
+        uses: actions/checkout@v3
+      - name: env up
+        shell: bash
+        working-directory: auto
+        id: env_up
+        env:
+          pull_policy: 'if_not_present'
+          GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
+          TYK_DB_LICENSEKEY: ${{ secrets.DASH_LICENSE }}
+          TYK_MDCB_LICENSE: ${{ secrets.MDCB_LICENSE }}
+          ECR: ${{ steps.ecr.outputs.registry }}
+        run: |
+          echo "ECR=${ECR}
+          tyk_image=$ECR/tyk:master
+          tyk_analytics_image=$ECR/tyk-analytics:master
+          # alfa and beta have to come after the override
+          tyk_alfa_image=$tyk_image
+          tyk_beta_image=$tyk_image
+          tyk_pump_image=${{matrix.pump}}
+          tyk_sink_image=${{matrix.sink}}
+          confs_dir=./pro-ha
+          env_file=local-${{ matrix.db }}.env" > versions.env
+          echo "::group::versions"
+          cat versions.env
+          echo "::endgroup::"
+          # Add Tyk component config variations to $env_file
+          cat confs/${{ matrix.conf }}.env >> local-${{ matrix.db }}.env
+          # bring up env, the project name is important
+          docker compose -p auto -f pro-ha.yml -f deps_pro-ha.yml -f ${{ matrix.db }}.yml -f ${{ matrix.cache_db }}.yml --env-file versions.env --profile master-datacenter up --quiet-pull -d
+          ./dash-bootstrap.sh http://localhost:3000
+          docker compose -p auto -f pro-ha.yml -f deps_pro-ha.yml -f ${{ matrix.db }}.yml -f ${{ matrix.cache_db }}.yml --env-file versions.env --profile slave-datacenter up --quiet-pull -d
+      - name: Install Node.js 18.16
+        uses: actions/setup-node@v2.4.1
+        with:
+          node-version: 18.16
+      - name: Fix private module deps
+        env:
+          TOKEN: '${{ secrets.ORG_GH_TOKEN }}'
+        run: "git config --global url.\"https://${TOKEN}@github.com\".insteadOf \"https://github.com\"                    \n"
+      - name: Checkout of Dashboard
+        uses: actions/checkout@v4
+        with:
+          repository: TykTechnologies/tyk-analytics
+          fetch-depth: 1
+          token: ${{ secrets.ORG_GH_TOKEN }}
+          sparse-checkout: |
+            tests/ui
+            bin
+          submodules: false
+      - name: Install test dependecies
+        run: |
+          npm ci
+        working-directory: tests/ui
+      - name: Install Playwright Browsers
+        run: npx playwright install --with-deps
+        working-directory: tests/ui
+      - name: Execute UI tests
+        id: test_execution
+        run: |
+          # Generate report id
+          echo "id=$(date +%s%N)" >> $GITHUB_OUTPUT
+          npm run test -- --workers=3
+        working-directory: tests/ui
+        env:
+          GW_URL: 'https://localhost:8080/'
+          NODE_TLS_REJECT_UNAUTHORIZED: 0
+          SLACK_AUTH_TOKEN: ${{ secrets.UI_SLACK_AUTH_TOKEN }}
+          EVENT_TRIGGER: ${{ github.event_name }} (${{ github.actor }})
+          JOB_RUN_ID: ${{ github.run_id }}
+          JOB_NAME: tyk-analytics - ${{ github.ref }} ${{ github.event.head_commit.message }}
+          RUN_ID: 'tyk-analytics/${{ github.run_id }}'
+      - name: Docker logs for all components
+        if: failure() && (steps.test_execution.outcome != 'success' || steps.env_up.outcome != 'success')
+        working-directory: auto
+        env:
+          pull_policy: 'if_not_present'
+          GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
+          TYK_DB_LICENSEKEY: ${{ secrets.DASH_LICENSE }}
+          TYK_MDCB_LICENSE: ${{ secrets.MDCB_LICENSE }}
+          ECR: ${{ steps.ecr.outputs.registry }}
+        run: |
+          docker compose -p auto -f pro-ha.yml -f deps_pro-ha.yml -f ${{ matrix.db }}.yml -f ${{ matrix.cache_db }}.yml --env-file versions.env --profile all logs | sort > ${{ github.workspace }}/docker-compose.log
+          echo "::group::DockerLogs"
+          cat ${{ github.workspace }}/docker-compose.log
+          echo "::endgroup::"
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        if: failure() && (steps.test_execution.outcome != 'success' || steps.env_up.outcome != 'success')
+        with:
+          name: docker-compose-logs-${{ github.job }}-${{ matrix.db }}-${{ matrix.conf }}-${{ github.run_id }}
+          path: ${{ github.workspace }}/docker-compose.log
+          retention-days: 3
+          overwrite: true
   release:
     if: github.event_name != 'pull_request'
     runs-on: ubuntu-latest
-    needs: [api-tests, ui-tests]
+    needs: [api-tests,ui-tests]
     permissions:
       contents: write  
     steps:
